font:
  normal:
    family: DroidSansMono Nerd Font
    style: Regular
  bold:
    family: DroidSansMono Nerd Font
    style: Bold
  italic:
    family: DroidSansMono Nerd Font
    style: Italic
  bold_italic:
    family: DroidSansMono Nerd Font
    style: Bold Italic
  size: 11.0
